apiVersion: vib.alexandre.mahdhaoui.com/v1alpha1
kind: ExpressionSet
metadata:
    name: env
spec:
    keyValues:
    - GOPATH: $(go env GOPATH)
    - GOBIN: ${GOPATH}/bin
    - PATH: ${PATH}:${GOBIN}
    resolverRef: environment-exported
